//rock, paper, scissors for player sprite
let mission12 = {
	numberSteps : 15,
	steps: [
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission","tutor.menu.mission"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models"],
			init: {
				text: "Let's put our model to use shall we! Under the when I receive new move section block, put a block from\
				 the Watson extension that will choose a model from a list. Choose the Rock Paper Scissors model."
			},
			ok: {
				text: "Great job! Onto the next step."
			},
			bad_block: {
				text: "Oh no! That's not the right block."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models", "data_setvariableto","text"],
			init: {
				text: "Now let's store the results of our model in a variable. So you should use a set variable block and \
				choose the variable to set to you."
			},
			ok: {
				text: "Very good!"
			},
			bad_block: {
				text: "Not quite, try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models", "data_setvariableto","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models", "data_setvariableto","text", 
			"watson.recognizeObject","text"],
			init: {
				text: "We want Watson to set you to a picture that you have trained it to recognize. So let's fill in the\
				blank space in the variable block to a block that will recognize objects in a photo. This block will be under\
				the Watson extension."
			},
			ok: {
				text: "Awesome!"
			},
			bad_block: {
				text: "No, that's not quite it. Look for the magic block under the Watson extension."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models", "data_setvariableto","text", 
			"watson.recognizeObject","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission","tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text","watson.recognizeObject","text","data_variable"],				
			init: {
				text: "We want to change the message that we are broadcasting now, so that we can automatically switch into\
				the right costume depending on the image that Watson recognizes. Add a new message to the broadcast block in\
				the menu and have the message be set my costume. \\ Under the next section, change the receiving\
				block to receive our set my costume message. \\ Then, in the set variable block set you the you variable to itself."
			},
			ok: {
				text: "Good job!"
			},
			bad_block: {
				text: "Oops! Try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if"],
			init: {
				text: "We can check what we've set our costume with, by using an if statement to check if a certain\
				condition is true or not. Take an if block from control and wrap it around the Set costume block."
			},
			ok: {
				text: "Awesome!"
			},
			bad_block: {
				text: "Oops! Use an if block from control."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text"],
			init: {
				text: "Let's fill in the if control now. The condition we want to check is equality, whether or not\
				our you variable equals rock or not. So we should place an equals operator block into the if block."
			},
			ok: {
				text: "You're doing great!"
			},
			bad_block: {
				text: "Oh no! That's not the right block."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable"],
			init: {
				text: "Let's fill in the operator block now. In one of the spaces, put in the you variable block.\
				In the other one, write in rock. This if block now checks if the you variable is equal to rock."
			},
			ok: {
				text: "You're doing great! You've finished changing one section, now let's go change the other two."
			},
			bad_block: {
				text: "Oh no! That's not it. Remember to use the you variable from under variables."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable"],
			init: {
				text: "Repeat what we did above with the paper receiving section now. Come on, you know what to do:\
				Change the receiving block to receive set my costume instead, then set the variable block to you."
			},
			ok: {
				text: "Good job!"
			},
			bad_block: {
				text: "Oops! Try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if"],
			init: {
				text: "Time to add in that if block around set costume."
			},
			ok: {
				text: "Perfect!"
			},
			bad_block: {
				text: "Oops! Remember what you did for the last section."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text"],
			init: {
				text: "Inside the if block, let's put in an empty equals operator."
			},
			ok: {
				text: "Good job! You're really getting the hang of this."
			},
			bad_block: {
				text: "Oops! Use the block you did in the last section!"
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable"],
			init: {
				text: "Now it's time to fill in the equals operator with the you variable. In the other blank make sure\
				you write paper."
			},
			ok: {
				text: "Awesome! Let's move on to the last section."
			},
			bad_block: {
				text: "Oh no! You're so close. Try again"
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable"],
			init: {
				text: "You're a pro now. Let's start with setting the set you variable block to itself and changing the receiving\
				message."
			},
			ok: {
				text: "Great job!"
			},
			bad_block: {
				text: "Mmmmm no quite, let's try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if"],
			init: {
				text: "Ok, now let's put in that if block."
			},
			ok: {
				text: "Great job! We're almost there."
			},
			bad_block: {
				text: "Oops! Try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if", "operator_equals","text","text"],
			init: {
				text: "Almost there, now let's put in that equals operator. You know where it goes."
			},
			ok: {
				text: "Great job!"
			},
			bad_block: {
				text: "Oh no, try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if", "operator_equals","text","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if", "operator_equals","text","text", "data_variable"],
			init: {
				text: "Last step: fill in the equals operator with a you variable and the word scissors."
			},
			ok: {
				text: "You have completed the mission!."
			},
			bad_block: {
				text: "Oops! Try again, you're almost there."
			}
		}
	]
};
module.exports = mission12;