//rock, paper, scissors for player sprite
let mission13 = {
	numberSteps : 15,
	steps: [
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission","tutor.menu.mission"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models"],
			init: {
				text: "Let's put our model to use shall we! Under the when I receive new move section block, put a block from\
				 the Watson extension that will choose our rock paper scissors model from a list."
			},
			ok: {
				text: "Great job! Onto the next step."
			},
			bad_block: {
				text: "Oh no! That's not the right block."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models", "data_setvariableto","text"],
			init: {
				text: "Now let's store the results of our model in a variable. Which block should we use for that?"
			},
			ok: {
				text: "Very good!"
			},
			bad_block: {
				text: "Not quite, try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models", "data_setvariableto","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models", "data_setvariableto","text", 
			"watson.recognizeObject","text"],
			init: {
				text: "We want Watson to set you to a picture that you have trained it to recognize. Where can we find a block\
				that will recognize an image?"
			},
			ok: {
				text: "Awesome!"
			},
			bad_block: {
				text: "No, that's not quite it. Look for the magic block under the Watson extension."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text",
			"event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if",
			"operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say",
			"text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals",
			"text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if",
			"operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say",
			"text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals",
			"text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast",
			"event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu",
			"event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number", "tutor.mission", 
			"tutor.menu.mission", "watson.getModelFromList","watson.menu.models", "data_setvariableto","text", 
			"watson.recognizeObject","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast","event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived","control_if","operator_equals","text","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if","operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked","looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission","tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text","watson.recognizeObject","text","data_variable"],				
			init: {
				text: "We want to change the message that we are broadcasting now. Add a new message to the broadcast block in\
				the menu and have the message be set my costume. \\ But now, how can we make sure this message is received?\
				After you're done, in the set variable block set you the you variable to itself."
			},
			ok: {
				text: "Good job!"
			},
			bad_block: {
				text: "Oops! Try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if"],
			init: {
				text: "How can we check what we have set our costume to? What kind of control block does that? Where\
				should you put this block so that we switch our costume."
			},
			ok: {
				text: "Awesome!"
			},
			bad_block: {
				text: "Oops! Use an if block from control."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text"],
			init: {
				text: "Now, instead our if block, we need some sort of operator that will check if two statements\
				are equal or not. What kind of block does that?"
			},
			ok: {
				text: "You're doing great!"
			},
			bad_block: {
				text: "Oh no! That's not the right block."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable"],
			init: {
				text: "Which two statements or variables are we trying to compare to each other in order to figure\
				out what costume you should wear? What do you want to happen when the two statements are equal to\
				each other?"
			},
			ok: {
				text: "You're doing great! You've finished changing one section, now let's go change the other two."
			},
			bad_block: {
				text: "Oh no! That's not it. Remember to use the you variable from under variables."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable"],
			init: {
				text: "Now let's repeat what we just did for the paper section. Come on, you know what to do."
			},
			ok: {
				text: "Good job!"
			},
			bad_block: {
				text: "Oops! Try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if"],
			init: {
				text: "Time to add in another control block. Do you remember which one it is?"
			},
			ok: {
				text: "Perfect!"
			},
			bad_block: {
				text: "Oops! Remember what you did for the last section."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text"],
			init: {
				text: "Now what do we put inside the if block?"
			},
			ok: {
				text: "Good job! You're really getting the hang of this."
			},
			bad_block: {
				text: "Oops! Use the block you did in the last section!"
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable"],
			init: {
				text: "This next step is very similar to what we did before. Except, instead of rock, what move are\
				we checking for this time?"
			},
			ok: {
				text: "Awesome! Let's move on to the last section."
			},
			bad_block: {
				text: "Oh no! You're so close. Try again"
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable"],
			init: {
				text: "You're a pro now. Do you remember what to do for this last section?"
			},
			ok: {
				text: "Great job!"
			},
			bad_block: {
				text: "Mmmmm no quite, let's try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if"],
			init: {
				text: "Ok, now let's wrap a control block around the switch costume block."
			},
			ok: {
				text: "Great job! We're almost there."
			},
			bad_block: {
				text: "Oops! Try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if", "operator_equals","text","text"],
			init: {
				text: "Almost there, now let's fill out that empty if block."
			},
			ok: {
				text: "Great job!"
			},
			bad_block: {
				text: "Oh no, try again."
			}
		},
		{
			init_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if", "operator_equals","text","text"],
			end_blocks: ["event_whenbroadcastreceived","data_setvariableto","text","event_broadcast",
			"event_broadcast_menu","looks_switchcostumeto","looks_costume","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","looks_say","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","data_variable","text",
			"text","looks_say","text","control_if","operator_equals","text","text","looks_say","text",
			"control_if","operator_equals","text","text","looks_say","text","event_whenbroadcastreceived",
			"control_if","operator_equals","text","text","control_if","operator_equals","text","text",
			"looks_say","text","control_if","operator_equals","text","text","looks_say","text","control_if",
			"operator_equals","data_variable","text","text","looks_say","text","data_variable","data_variable",
			"data_variable","data_variable","data_variable","data_variable","data_variable","data_variable",
			"data_variable","event_broadcast","event_broadcast_menu","event_whenbroadcastreceived",
			"event_whenbroadcastreceived","data_setvariableto","text","looks_switchcostumeto","looks_costume",
			"event_broadcast","event_broadcast_menu","event_whenbroadcastreceived","data_setvariableto","text",
			"looks_switchcostumeto","looks_costume","event_broadcast","event_broadcast_menu","event_whenflagclicked",
			"looks_switchcostumeto","looks_costume","control_wait","math_positive_number","tutor.mission",
			"tutor.menu.mission","watson.getModelFromList","watson.menu.models","data_setvariableto","text",
			"watson.recognizeObject","text","data_variable", "control_if", "operator_equals","text","text", 
			"data_variable", "data_variable", "control_if", "operator_equals","text","text", "data_variable", 
			"data_variable", "control_if", "operator_equals","text","text", "data_variable"],
			init: {
				text: "Last step: fill in the equals operator. What move is left to check?"
			},
			ok: {
				text: "You have completed the mission!."
			},
			bad_block: {
				text: "Oops! Try again, you're almost there."
			}
		}
	]
};
module.exports = mission13;